# Logging Configuration
#
# This file configures logging behavior for all projects.

logging:
  # Global log level: DEBUG, INFO, WARNING, ERROR, CRITICAL
  level: "INFO"
  
  # Log format
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Date format
  date_format: "%Y-%m-%d %H:%M:%S"
  
  # Project-specific log files
  files:
    project1: "01-skill-specification-extraction/extraction.log"
    project2: "02-skill-redundancy-relationships/redundancy.log"
    project3: "03-base-skills-taxonomy/taxonomy.log"
    shared: "shared.log"
  
  # Console output
  console:
    enabled: true
    level: "INFO"
  
  # File output
  file:
    enabled: true
    level: "DEBUG"
    max_bytes: 10485760  # 10 MB
    backup_count: 5

