# LLM Model Configuration
#
# This file configures AWS Bedrock model settings for all projects.
# AWS credentials should be configured via AWS CLI or environment variables.

bedrock:
  region: "us-west-2"
  profile: "ai-poc"
  default_model: "claude-3-5-v2"
  
  models:
    claude-3: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
    claude-3-5-v2: "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
    claude-instant: "anthropic.claude-instant-v1"
    titan: "amazon.titan-text-express-v1"
  
  defaults:
    temperature: 0.1
    max_tokens: 1000
    
  # Cost tracking (approximate, in USD per 1K tokens)
  pricing:
    claude-3-5-v2:
      input: 0.00025
      output: 0.00125
    claude-3:
      input: 0.00025
      output: 0.00125

